/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root.tsx"
import { Route as PayCodeImport } from "./routes/pay/$code.tsx"

// Create/Update Routes

const PayCodeRoute = PayCodeImport.update({
  id: "/pay/$code",
  path: "/pay/$code",
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/pay/$code": {
      id: "/pay/$code"
      path: "/pay/$code"
      fullPath: "/pay/$code"
      preLoaderRoute: typeof PayCodeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/pay/$code": typeof PayCodeRoute
}

export interface FileRoutesByTo {
  "/pay/$code": typeof PayCodeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/pay/$code": typeof PayCodeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/pay/$code"
  fileRoutesByTo: FileRoutesByTo
  to: "/pay/$code"
  id: "__root__" | "/pay/$code"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PayCodeRoute: typeof PayCodeRoute
}

const rootRouteChildren: RootRouteChildren = {
  PayCodeRoute: PayCodeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/pay/$code"
      ]
    },
    "/pay/$code": {
      "filePath": "pay/$code.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
